### ISSUE TITLE
[bug] config.js 파일 충돌 수정 

### ISSUE THREAD

**Issue by Seungwoo321** [joshua1988/vue-camp#118]
https://github.com/joshua1988/vue-camp/blob/master/docs/.vuepress/config.js#L218-L219

config.js 의 충돌내용이 수정되지 않은 상태로 pr 반영 된 것 같습니다.

**Comment by Parkjju** [comment]
아이고 제가 이슈를 먼저 할당하고 작업했어야 했는데
죄송합니다 승우님😭

**Comment by Seungwoo321** [comment]
아니에요 ㅎㅎ 수고하셨습니다!!
