### ISSUE TITLE
[문서] Open Source에서 Pull Request 하기

### ISSUE THREAD

**Issue by jm-chong** [joshua1988/vue-camp#24]
Open Source Project의 소스를 수정하고 Pull Request 를 어떻게 하는지에 대해 문서화 합니다.
- Repository Fork
- Pull Request to Origin Repository
의 내용을 작성하고자 합니다.

참고자료
- [How to create a pull request on github](https://egghead.io/lessons/javascript-how-to-create-a-pull-request-on-github)
- [What open source project should I contribute to](https://kentcdodds.com/blog/what-open-source-project-should-i-contribute-to)

**Comment by joshua1988** [comment]
@jm-chong 오 재명님 좋습니다 😄 늦은 시간에... ㅎㅎ 어서 주무셔요. 그리고 이거 이슈에 올린 것들은 저희 깃헙 프로젝트 탭에서도 진행 현황이랑 연동되면 좋을 것 같은데 그런 기능이 있으려나요..? ㅋㅋ 회사에서는 너무 젠허브만 쓴 듯... ㅋㅋ 조금 전에 깃헙 액션 셋업하는데 재밌네요 ㅋㅋ

**Comment by amorfati0310** [comment]
> @jm-chong 오 재명님 좋습니다 😄 늦은 시간에... ㅎㅎ 어서 주무셔요. 그리고 이거 이슈에 올린 것들은 저희 깃헙 프로젝트 탭에서도 진행 현황이랑 연동되면 좋을 것 같은데 그런 기능이 있으려나요..? ㅋㅋ 회사에서는 너무 젠허브만 쓴 듯... ㅋㅋ 조금 전에 깃헙 액션 셋업하는데 재밌네요 ㅋㅋ

![스크린샷 2021-08-11 오후 11 42 29](https://user-images.githubusercontent.com/25189066/129050185-af6e4e8e-06e1-4b7a-aaee-713148ad521e.png)
프프로젝트 클릭해서 상태 연결시키면 적용되네요 👍

**Comment by jm-chong** [comment]
기술부채 청산중입니다. 휴가가야돼요. ㅎㅎㅎ
