### ISSUE TITLE
[docs] HOW_TO_CONTRIBUTE.md 문서에 있는 오타 수정

### ISSUE THREAD

**Issue by zwonlala** [joshua1988/vue-camp#40]
[HOW_TO_CONTRIBUTE.md](https://github.com/joshua1988/vue-camp/blob/master/.github/HOW_TO_CONTRIBUTE.md#create-pull-request) 문서의 'Create Pull Request' 부분에 보면

`remote` 라고 나와야 하는 부분이 
`emote`라고 나와 있다.

![스크린샷 2021-08-15 오후 10 10 50](https://user-images.githubusercontent.com/13375734/129479720-65decbfd-cfb7-4f58-9b3b-4ea5001f6b92.jpg)

해당 오타를 수정하는 이슈

**Comment by Parkjju** [comment]
해당 이슈 제가 수정해보도록 하겠습니다!
