### ISSUE TITLE
[tool] 사이트 툴링 아이디어 리스트

### ISSUE THREAD

**Issue by yahma25** [joshua1988/vue-camp#74]
# 사이트 툴링 아이디어 리스트

## Github Actions
정기적으로 vue 관련 article 수집(크롤링) 및 게시
* 일반 개발 article
* 공식 문서
* 등등

🙄 Actions를 이용해서 재미있는 아이디어가 생각이 날듯~ 말듯~ 하네요~

<br/>

## 테스트 코드 자동화
개인적으론 자동화의 꽃이라고 생각하는데 테스트 코드가 없군요... 😢 
* 🤔 어떤 테스트 코드를 작성해볼 수 있을까요?

<br/>

## 404 페이지 꾸미기
길을 잃은 학습자에게 나아갈 길을 안내해주세요!
* 현재 상태를 알려주는 친절한 설명과 기본 페이지로 안내해주기
  * 메인 페이지 또는 이전 페이지(브라우저 history 기준) 등등
* [github 404 예시](https://github.com/joshua1988/vue-campoo)

<br/>

## 다크 테마
흰바탕에 검은 글씨... 눈이 너무 침침하네요. 안구 보호해주실분~

<br/>

## 플러그인 ~~왕창~~ 설치하기
[VuePress Community Plugins](https://vuepress-community.netlify.app/en/)를 둘러보면서 우리 프로젝트에 쓸만한 게 있으면 설치해봐도 좋을 것 같아요!

### 해볼만한 플러그인

* [git-log](https://vuepress-community.netlify.app/en/plugins/git-log.html) 페이지에 문서 기여자 새기기 🤔 문서 가독성을 떨어트리지 않는 선에서 괜찮지 않을까요?
* [medium-zoom](https://vuepress-community.netlify.app/en/plugins/medium-zoom.html), [zooming](https://vuepress-community.netlify.app/en/plugins/zooming.html) 이미지 확대 효과 😏 정적 웹 페이지이긴 한데 너무 정적인거 아닐까요?
* [nprogress](https://vuepress-community.netlify.app/en/plugins/nprogress.html) 다른 문서 전환 시 로딩 진행률 (수정됨)
* [reading-progress](https://github.com/tolking/vuepress-plugin-reading-progress) 문서 읽기 진행률 (추가됨)
* 코드블록 복사하기

이 외 다양한 자료가 모여있는 [awesome-vuepress](https://github.com/vuepress/awesome-vuepress#plugins)에서 확인해보세요

**Comment by yahma25** [comment]
하고 싶으신 게 있으신분은 새로 이슈 만들어서 진행해주시면 될 것 같아요! 🚀

**Comment by Kyounghwan01** [comment]
다크모드는 이전부터 열심히 노력해봤는데 잘 안되더라구요.. ㅜ 참고로 vuepress v2 부터는 다크모드가 기본 config으로 제공되니 vuepress를 v2로 올리시는 작업도 도전해보시면 좋을꺼같아요!

https://v2.vuepress.vuejs.org/reference/default-theme/config.html#logodark

**Comment by sewonkimm** [comment]
오 정말 유용한 플러그인들이 많네요...! 
문서 읽기 진행률 확인하는 nprogress는 필요하다고 생각했는데 제가 적용해보겠습니다! ㅎㅎ

**Comment by sewonkimm** [comment]
검색해보니 nprogress는 문서읽기 진행률을 나타내는 플러그인이 아니라 다른 페이지로 이동할 때 로딩바 같은 개념이었네요 ^^,,,
문서읽기 진행률은 다른 플러그인을 찾아보겠습니다~

**Comment by yahma25** [comment]
@sewonkimm 
🙈 아이고 제가 본건 [vuepress-plugin-reading-progress](https://github.com/tolking/vuepress-plugin-reading-progress) 이거였나봐요. 계속 돌아다니다 보니 progress만 보고 가져온거 같네요.

**Comment by scl2589** [comment]
진짜 좋은 아이디어들이네요!! 
저도 우선 404 페이지를 꾸며보고, 다크 테마가 가능한지 찾아보겠습니다 ㅎㅎ
